CREATE TABLE IF NOT EXISTS members (
    member_id INT NOT NULL AUTO_INCREMENT,
    member_code VARCHAR(50) NOT NULL,
    member_type ENUM('Worker', 'Staff') NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100) DEFAULT '',
    last_name VARCHAR(100) NOT NULL,
    suffix VARCHAR(20) DEFAULT '',
    date_of_birth DATE DEFAULT NULL,
    sex ENUM('Male', 'Female', 'Prefer not to say') DEFAULT NULL,
    civil_status VARCHAR(30) DEFAULT '',
    contact_number VARCHAR(25) DEFAULT '',
    personal_email VARCHAR(150) DEFAULT '',
    address TEXT DEFAULT NULL,
    employee_number VARCHAR(50) DEFAULT '',
    position_title VARCHAR(150) DEFAULT '',
    department_name VARCHAR(150) DEFAULT '',
    date_joined DATE DEFAULT NULL,
    membership_status ENUM('Active', 'Probationary', 'Inactive', 'Pending') DEFAULT 'Pending',
    government_id_type VARCHAR(80) DEFAULT '',
    government_id_number VARCHAR(120) DEFAULT '',
    government_id_expiration DATE DEFAULT NULL,
    company_email VARCHAR(150) DEFAULT '',
    account_status ENUM('Unassigned', 'Active', 'Inactive', 'Pending') DEFAULT 'Unassigned',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (member_id),
    UNIQUE KEY uq_member_code (member_code),
    KEY idx_member_type (member_type),
    KEY idx_membership_status (membership_status),
    KEY idx_company_email (company_email),
    KEY idx_government_id_number (government_id_number),
    KEY idx_contact_number (contact_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS member_documents (
    document_id INT NOT NULL AUTO_INCREMENT,
    member_id INT NOT NULL,
    document_type VARCHAR(80) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) DEFAULT '',
    upload_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ocr_status ENUM('Pending', 'Processing', 'Completed', 'Failed') DEFAULT 'Pending',
    ocr_text LONGTEXT DEFAULT NULL,
    verification_status ENUM('Unverified', 'Verified', 'Rejected') DEFAULT 'Unverified',
    verified_by VARCHAR(120) DEFAULT '',
    verification_date DATETIME DEFAULT NULL,
    PRIMARY KEY (document_id),
    KEY idx_member_id (member_id),
    KEY idx_document_type (document_type),
    CONSTRAINT fk_member_documents_member FOREIGN KEY (member_id) REFERENCES members(member_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS accounts (
    account_id INT NOT NULL AUTO_INCREMENT,
    member_id INT NOT NULL,
    company_email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    account_status ENUM('Active', 'Inactive', 'Pending', 'Suspended') DEFAULT 'Pending',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login DATETIME DEFAULT NULL,
    email_status ENUM('Queued', 'Sent', 'Failed') DEFAULT 'Queued',
    email_sent_at DATETIME DEFAULT NULL,
    PRIMARY KEY (account_id),
    UNIQUE KEY uq_member_id (member_id),
    UNIQUE KEY uq_company_email (company_email),
    KEY idx_account_email (company_email),
    KEY idx_account_status (account_status),
    CONSTRAINT fk_accounts_member FOREIGN KEY (member_id) REFERENCES members(member_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
